


<!DOCTYPE html>
    <html lang="en" dir="ltr">
      <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="Support.css">
      </head>
      <body>
        <h1>Support Page</h1>
      <div>
        <form action="https://formsubmit.co/aybio.2021@gmail.com" method="POST">
         <p><textarea name="text" rows="8" cols="25" placeholder="Whats wrong?"></textarea></p>
         <input type="hidden" name="_next" value="http://localhost/wwwm/htmltot/THANKY.html">
         <p><input type="email" name="email" placeholder="Enter your email Please" required>
         <button type="submit">Send</button></p>

    </form>

      </div>
      </body>
    </html>
